cognitive-complexity-threshold = 25
too-many-arguments-threshold = 4
too-many-lines-threshold = 100
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
